/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file icons/back.png */
extern const unsigned char back_png[];

/* created by reswrap from file icons/back_small.png */
extern const unsigned char back_small_png[];

/* created by reswrap from file icons/bigfolder.gif */
extern const unsigned char bigfolder_gif[];

/* created by reswrap from file icons/bigfolderopen.gif */
extern const unsigned char bigfolderopen_gif[];

/* created by reswrap from file icons/clear_right.png */
extern const unsigned char clear_right_png[];

/* created by reswrap from file icons/compass.png */
extern const unsigned char compass_png[];

/* created by reswrap from file icons/copy.gif */
extern const unsigned char copy_gif[];

/* created by reswrap from file icons/critical.png */
extern const unsigned char critical_png[];

/* created by reswrap from file icons/cut.gif */
extern const unsigned char cut_gif[];

/* created by reswrap from file icons/delete.gif */
extern const unsigned char delete_gif[];

/* created by reswrap from file icons/exit.png */
extern const unsigned char exit_png[];

/* created by reswrap from file icons/forward.png */
extern const unsigned char forward_png[];

/* created by reswrap from file icons/forward_small.png */
extern const unsigned char forward_small_png[];

/* created by reswrap from file icons/gohome.png */
extern const unsigned char gohome_png[];

/* created by reswrap from file icons/gohome_small.png */
extern const unsigned char gohome_small_png[];

/* created by reswrap from file icons/info.png */
extern const unsigned char info_png[];

/* created by reswrap from file icons/link.gif */
extern const unsigned char link_gif[];

/* created by reswrap from file icons/lock.png */
extern const unsigned char lock_png[];

/* created by reswrap from file icons/logo.gif */
extern const unsigned char logo_gif[];

/* created by reswrap from file icons/minidoc.gif */
extern const unsigned char minidoc_gif[];

/* created by reswrap from file icons/minifolder.gif */
extern const unsigned char minifolder_gif[];

/* created by reswrap from file icons/move.gif */
extern const unsigned char move_gif[];

/* created by reswrap from file icons/paste.gif */
extern const unsigned char paste_gif[];

/* created by reswrap from file icons/settings.png */
extern const unsigned char settings_png[];

/* created by reswrap from file icons/tab_breakoff.png */
extern const unsigned char tab_breakoff_png[];

/* created by reswrap from file icons/tab_duplicate.png */
extern const unsigned char tab_duplicate_png[];

/* created by reswrap from file icons/tab_new.png */
extern const unsigned char tab_new_png[];

/* created by reswrap from file icons/tab_remove.png */
extern const unsigned char tab_remove_png[];

/* created by reswrap from file icons/up.png */
extern const unsigned char up_png[];

/* created by reswrap from file icons/up_small.png */
extern const unsigned char up_small_png[];

/* created by reswrap from file icons/warning.png */
extern const unsigned char warning_png[];

/* created by reswrap from file icons/window_new.png */
extern const unsigned char window_new_png[];

